2017/06/14 16:55:01 [error] 2468#0: *1 open() "/home/webserver/jwtServer/html/favicon.ico" failed (2: No such file or directory), client: 192.168.121.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.121.160", referrer: "http://192.168.121.160/sign"
2017/06/14 16:56:41 [notice] 2494#0: signal process started
2017/06/14 16:58:33 [emerg] 2497#0: unexpected "j" in /home/webserver/jwtServer/conf/nginx.conf:64
2017/06/14 16:59:24 [notice] 2499#0: signal process started
2017/06/14 16:59:30 [error] 2500#0: *9 failed to load inlined Lua code: content_by_lua(nginx.conf:67):5: unexpected symbol near '#', client: 192.168.121.1, server: localhost, request: "GET /verify HTTP/1.1", host: "192.168.121.160"
2017/06/14 16:59:38 [error] 2500#0: *10 failed to load inlined Lua code: content_by_lua(nginx.conf:67):5: unexpected symbol near '#', client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=123 HTTP/1.1", host: "192.168.121.160"
2017/06/14 16:59:47 [error] 2500#0: *11 failed to load inlined Lua code: content_by_lua(nginx.conf:67):5: unexpected symbol near '#', client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmb28iOiJiYXIifQ.VxhQcGihWyHuJeHhpUiq2FU7aW2s_3ZJlY6h1kdlmJY HTTP/1.1", host: "192.168.121.160"
2017/06/14 17:00:34 [notice] 2504#0: signal process started
2017/06/14 17:00:37 [error] 2505#0: *12 failed to load inlined Lua code: content_by_lua(nginx.conf:67):5: unexpected symbol near '#', client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmb28iOiJiYXIifQ.VxhQcGihWyHuJeHhpUiq2FU7aW2s_3ZJlY6h1kdlmJY HTTP/1.1", host: "192.168.121.160"
2017/06/14 17:00:50 [notice] 2506#0: signal process started
2017/06/14 17:01:46 [notice] 2520#0: signal process started
2017/06/14 17:03:48 [notice] 2523#0: signal process started
2017/06/15 09:59:52 [error] 2974#0: *1 "/mnt/hgfs/manager/jwtServer/html/index.html" is not found (2: No such file or directory), client: 192.168.121.1, server: localhost, request: "GET / HTTP/1.1", host: "192.168.121.160"
2017/06/15 09:59:53 [error] 2974#0: *1 open() "/mnt/hgfs/manager/jwtServer/html/favicon.ico" failed (2: No such file or directory), client: 192.168.121.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.121.160", referrer: "http://192.168.121.160/"
2017/06/15 10:10:49 [notice] 3018#0: signal process started
2017/06/15 10:11:11 [error] 3019#0: *6 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:20: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:11:22 [notice] 3020#0: signal process started
2017/06/15 10:11:24 [error] 3021#0: *7 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:20: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:11:42 [notice] 3022#0: signal process started
2017/06/15 10:12:33 [notice] 3024#0: signal process started
2017/06/15 10:13:15 [notice] 3026#0: signal process started
2017/06/15 10:17:38 [notice] 3028#0: signal process started
2017/06/15 10:17:41 [error] 3029#0: *13 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:17:41 [error] 3029#0: *14 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:17:41 [error] 3029#0: *15 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:17:41 [error] 3029#0: *16 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:17:43 [error] 3029#0: *17 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:17:43 [error] 3029#0: *18 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:17:43 [error] 3029#0: *19 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:17:46 [error] 3029#0: *20 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:17:46 [error] 3029#0: *21 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:17:46 [error] 3029#0: *22 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:17:51 [error] 3029#0: *23 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:17:56 [error] 3029#0: *24 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:17:56 [error] 3029#0: *25 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:17:56 [error] 3029#0: *26 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:18:07 [notice] 3030#0: signal process started
2017/06/15 10:18:08 [error] 3031#0: *27 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:18:08 [error] 3031#0: *28 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:18:08 [error] 3031#0: *29 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:18:15 [notice] 3032#0: signal process started
2017/06/15 10:18:18 [error] 3033#0: *30 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:18:18 [error] 3033#0: *31 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:18:18 [error] 3033#0: *32 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:18:19 [error] 3033#0: *33 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:18:19 [error] 3033#0: *34 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:18:19 [error] 3033#0: *35 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:25: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:18:31 [notice] 3034#0: signal process started
2017/06/15 10:18:33 [error] 3035#0: *36 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:23: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:18:33 [error] 3035#0: *37 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:23: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:18:33 [error] 3035#0: *38 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:23: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:19:12 [error] 3035#0: *39 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:23: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:19:12 [error] 3035#0: *41 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:23: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:20:12 [error] 3035#0: *42 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:23: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:20:15 [notice] 3038#0: signal process started
2017/06/15 10:20:40 [notice] 3040#0: signal process started
2017/06/15 10:20:53 [notice] 3042#0: signal process started
2017/06/15 10:21:01 [notice] 3044#0: signal process started
2017/06/15 10:26:08 [notice] 3069#0: signal process started
2017/06/15 10:26:10 [error] 3070#0: *51 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:24: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:26:11 [error] 3070#0: *52 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/jwt.lua:696: bad argument #1 to 'pairs' (table expected, got number)
stack traceback:
coroutine 0:
	[C]: in function 'pairs'
	/opt/openresty/site/lualib/resty/jwt.lua:696: in function 'validate_claims'
	/opt/openresty/site/lualib/resty/jwt.lua:728: in function 'verify'
	/mnt/hgfs/manager/jwtServer/lua/init.lua:24: in function </mnt/hgfs/manager/jwtServer/lua/init.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /verify?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.R2XF5tV77LhnCzkAVjN1sCyMWnUQjKe1yiYNyCXQFdY HTTP/1.1", host: "192.168.121.160"
2017/06/15 10:26:47 [notice] 3073#0: signal process started
2017/06/15 10:31:18 [notice] 3077#0: signal process started
2017/06/15 10:31:56 [notice] 3079#0: signal process started
2017/06/15 10:37:12 [notice] 3104#0: signal process started
2017/06/15 10:38:31 [notice] 3107#0: signal process started
2017/06/15 10:40:14 [notice] 3111#0: signal process started
2017/06/15 10:43:53 [notice] 3113#0: signal process started
2017/06/15 10:45:58 [notice] 3115#0: signal process started
2017/06/15 10:46:40 [notice] 3117#0: signal process started
2017/06/15 11:05:54 [notice] 3421#0: signal process started
2017/06/15 11:06:08 [notice] 3423#0: signal process started
2017/06/15 11:16:13 [notice] 3450#0: signal process started
2017/06/15 11:18:00 [notice] 3452#0: signal process started
2017/06/15 11:19:50 [notice] 3455#0: signal process started
2017/06/15 11:20:19 [notice] 3459#0: signal process started
2017/06/15 14:59:27 [notice] 3906#0: signal process started
2017/06/16 09:38:52 [emerg] 4711#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2017/06/16 09:38:52 [emerg] 4711#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2017/06/16 09:38:52 [emerg] 4711#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2017/06/16 09:38:52 [emerg] 4711#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2017/06/16 09:38:52 [emerg] 4711#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2017/06/16 09:38:52 [emerg] 4711#0: still could not bind()
2017/06/16 09:38:57 [notice] 4712#0: signal process started
2017/06/16 09:41:42 [notice] 4720#0: signal process started
2017/06/16 09:41:43 [notice] 4722#0: signal process started
2017/06/16 09:43:02 [notice] 4724#0: signal process started
2017/06/16 10:06:04 [notice] 4792#0: signal process started
2017/06/16 10:07:40 [notice] 4794#0: signal process started
2017/06/16 10:09:02 [notice] 6245#0: signal process started
2017/06/16 10:17:48 [notice] 6272#0: signal process started
2017/06/16 10:23:37 [notice] 6276#0: signal process started
2017/06/16 10:24:37 [notice] 6278#0: signal process started
2017/06/16 10:24:41 [error] 6279#0: *43 open() "/mnt/hgfs/manager/jwtServer/html/favicon.ico" failed (2: No such file or directory), client: 192.168.121.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.121.160", referrer: "http://192.168.121.160/123.html"
2017/06/16 10:37:44 [notice] 6305#0: signal process started
2017/06/16 11:06:23 [notice] 6400#0: signal process started
2017/06/16 11:06:24 [notice] 6402#0: signal process started
2017/06/16 11:06:27 [error] 6403#0: *62 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/waf/log.lua:23: could not find 11000_whitelist
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/opt/openresty/site/lualib/resty/waf/log.lua:23: in function 'fatal_fail'
	/opt/openresty/site/lualib/resty/waf.lua:463: in function 'exec'
	/mnt/hgfs/manager/jwtServer/lua/verify.lua:40: in function </mnt/hgfs/manager/jwtServer/lua/verify.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0OTc1ODM0NDguMDYxLCJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.5_LnD6jseAmCkv9KGGfLYQjZ1anKA2O0LeYykSracd4 HTTP/1.1", host: "192.168.121.160"
2017/06/16 11:06:33 [error] 6403#0: *63 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/waf/log.lua:23: could not find 11000_whitelist
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/opt/openresty/site/lualib/resty/waf/log.lua:23: in function 'fatal_fail'
	/opt/openresty/site/lualib/resty/waf.lua:463: in function 'exec'
	/mnt/hgfs/manager/jwtServer/lua/verify.lua:40: in function </mnt/hgfs/manager/jwtServer/lua/verify.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0OTc1ODM0NDguMDYxLCJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.5_LnD6jseAmCkv9KGGfLYQjZ1anKA2O0LeYykSracd4 HTTP/1.1", host: "192.168.121.160"
2017/06/16 11:06:35 [error] 6403#0: *64 lua entry thread aborted: runtime error: /opt/openresty/site/lualib/resty/waf/log.lua:23: could not find 11000_whitelist
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/opt/openresty/site/lualib/resty/waf/log.lua:23: in function 'fatal_fail'
	/opt/openresty/site/lualib/resty/waf.lua:463: in function 'exec'
	/mnt/hgfs/manager/jwtServer/lua/verify.lua:40: in function </mnt/hgfs/manager/jwtServer/lua/verify.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0OTc1ODM0NDguMDYxLCJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.5_LnD6jseAmCkv9KGGfLYQjZ1anKA2O0LeYykSracd4 HTTP/1.1", host: "192.168.121.160"
2017/06/16 11:10:24 [error] 6441#0: [lua] waf.lua:586: init(): could not find 11000_whitelist
2017/06/16 11:10:24 [error] 6441#0: [lua] waf.lua:586: init(): could not find 20000_http_violation
2017/06/16 11:10:24 [error] 6441#0: [lua] waf.lua:586: init(): could not find 21000_http_anomaly
2017/06/16 11:10:24 [error] 6441#0: [lua] waf.lua:586: init(): could not find 35000_user_agent
2017/06/16 11:10:24 [error] 6441#0: [lua] waf.lua:586: init(): could not find 40000_generic_attack
2017/06/16 11:10:24 [error] 6441#0: [lua] waf.lua:586: init(): could not find 41000_sqli
2017/06/16 11:10:24 [error] 6441#0: [lua] waf.lua:586: init(): could not find 42000_xss
2017/06/16 11:10:24 [error] 6441#0: [lua] waf.lua:586: init(): could not find 90000_custom
2017/06/16 11:10:24 [error] 6441#0: [lua] waf.lua:586: init(): could not find 99000_scoring
2017/06/16 11:10:24 [notice] 6441#0: signal process started
2017/06/16 11:10:24 [error] 4535#0: [lua] waf.lua:586: init(): could not find 11000_whitelist
2017/06/16 11:10:24 [error] 4535#0: [lua] waf.lua:586: init(): could not find 20000_http_violation
2017/06/16 11:10:24 [error] 4535#0: [lua] waf.lua:586: init(): could not find 21000_http_anomaly
2017/06/16 11:10:24 [error] 4535#0: [lua] waf.lua:586: init(): could not find 35000_user_agent
2017/06/16 11:10:24 [error] 4535#0: [lua] waf.lua:586: init(): could not find 40000_generic_attack
2017/06/16 11:10:24 [error] 4535#0: [lua] waf.lua:586: init(): could not find 41000_sqli
2017/06/16 11:10:24 [error] 4535#0: [lua] waf.lua:586: init(): could not find 42000_xss
2017/06/16 11:10:24 [error] 4535#0: [lua] waf.lua:586: init(): could not find 90000_custom
2017/06/16 11:10:24 [error] 4535#0: [lua] waf.lua:586: init(): could not find 99000_scoring
2017/06/16 11:55:21 [emerg] 6535#0: "init_by_lua_file" directive is not allowed here in /mnt/hgfs/manager/jwtServer/conf/nginx.conf:63
2017/06/16 11:55:58 [emerg] 6559#0: "init_by_lua_file" directive is not allowed here in /mnt/hgfs/manager/jwtServer/conf/nginx.conf:63
2017/06/16 11:56:17 [notice] 6560#0: signal process started
2017/06/16 11:57:01 [error] 6561#0: *66 lua entry thread aborted: runtime error: /mnt/hgfs/manager/jwtServer/lua/verify.lua:9: module 'resty.jwt' not found:
	no field package.preload['resty.jwt']
	no file '/mnt/hgfs/manager/jwtServer/lua/waf/resty/jwt.lua'
	no file '/opt/openresty/site/lualib/resty/jwt.so'
	no file '/opt/openresty/lualib/resty/jwt.so'
	no file './resty/jwt.so'
	no file '/usr/local/lib/lua/5.1/resty/jwt.so'
	no file '/opt/openresty/luajit/lib/lua/5.1/resty/jwt.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/opt/openresty/site/lualib/resty.so'
	no file '/opt/openresty/lualib/resty.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/opt/openresty/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/mnt/hgfs/manager/jwtServer/lua/verify.lua:9: in function </mnt/hgfs/manager/jwtServer/lua/verify.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0OTc1ODM0NDguMDYxLCJuYW1lIjoibWluZDAyOSIsImZvbyI6ImJhciIsImlkIjoxfQ.5_LnD6jseAmCkv9KGGfLYQjZ1anKA2O0LeYykSracd4 HTTP/1.1", host: "192.168.121.160"
2017/06/16 11:57:03 [error] 6561#0: *67 lua entry thread aborted: runtime error: /mnt/hgfs/manager/jwtServer/lua/sign.lua:14: module 'resty.jwt' not found:
	no field package.preload['resty.jwt']
	no file '/mnt/hgfs/manager/jwtServer/lua/waf/resty/jwt.lua'
	no file '/opt/openresty/site/lualib/resty/jwt.so'
	no file '/opt/openresty/lualib/resty/jwt.so'
	no file './resty/jwt.so'
	no file '/usr/local/lib/lua/5.1/resty/jwt.so'
	no file '/opt/openresty/luajit/lib/lua/5.1/resty/jwt.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/opt/openresty/site/lualib/resty.so'
	no file '/opt/openresty/lualib/resty.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/opt/openresty/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/mnt/hgfs/manager/jwtServer/lua/sign.lua:14: in function </mnt/hgfs/manager/jwtServer/lua/sign.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /sign HTTP/1.1", host: "192.168.121.160"
2017/06/16 11:58:29 [notice] 6562#0: signal process started
2017/06/16 12:01:02 [notice] 6577#0: signal process started
2017/06/16 12:01:34 [notice] 6579#0: signal process started
2017/06/16 14:06:17 [notice] 6833#0: signal process started
2017/06/16 14:06:30 [error] 6834#0: *87 lua entry thread aborted: runtime error: /mnt/hgfs/manager/jwtServer/lua/access.lua:10: module '/mnt/hgfs/manager/jwtServer/lua/waf/waf.lua' not found:
	no field package.preload['/mnt/hgfs/manager/jwtServer/lua/waf/waf.lua']
	no file '/mnt/hgfs/manager/jwtServer/lua/waf//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/opt/openresty/site/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/opt/openresty/site/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua/init.lua'
	no file '/opt/openresty/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/opt/openresty/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua/init.lua'
	no file './/mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/opt/openresty/luajit/share/luajit-2.1.0-beta2//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/usr/local/share/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/usr/local/share/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua/init.lua'
	no file '/opt/openresty/luajit/share/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/opt/openresty/luajit/share/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua/init.lua'
	no file '/opt/openresty/site/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.so'
	no file '/opt/openresty/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.so'
	no file './/mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.so'
	no file '/usr/local/lib/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.so'
	no file '/opt/openresty/luajit/lib/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/opt/openresty/site/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf.so'
	no file '/opt/openresty/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf.so'
	no file './/mnt/hgfs/manager/jwtServer/lua/waf/waf.so'
	no file '/usr/local/lib/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf.so'
	no file '/opt/openresty/luajit/lib/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/mnt/hgfs/manager/jwtServer/lua/access.lua:10: in function </mnt/hgfs/manager/jwtServer/lua/access.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index?id=../etc/passwd HTTP/1.1", host: "192.168.121.160"
2017/06/16 14:06:34 [error] 6834#0: *89 lua entry thread aborted: runtime error: /mnt/hgfs/manager/jwtServer/lua/access.lua:10: module '/mnt/hgfs/manager/jwtServer/lua/waf/waf.lua' not found:
	no field package.preload['/mnt/hgfs/manager/jwtServer/lua/waf/waf.lua']
	no file '/mnt/hgfs/manager/jwtServer/lua/waf//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/opt/openresty/site/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/opt/openresty/site/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua/init.lua'
	no file '/opt/openresty/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/opt/openresty/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua/init.lua'
	no file './/mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/opt/openresty/luajit/share/luajit-2.1.0-beta2//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/usr/local/share/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/usr/local/share/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua/init.lua'
	no file '/opt/openresty/luajit/share/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/opt/openresty/luajit/share/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua/init.lua'
	no file '/opt/openresty/site/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.so'
	no file '/opt/openresty/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.so'
	no file './/mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.so'
	no file '/usr/local/lib/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.so'
	no file '/opt/openresty/luajit/lib/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/opt/openresty/site/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf.so'
	no file '/opt/openresty/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf.so'
	no file './/mnt/hgfs/manager/jwtServer/lua/waf/waf.so'
	no file '/usr/local/lib/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf.so'
	no file '/opt/openresty/luajit/lib/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/mnt/hgfs/manager/jwtServer/lua/access.lua:10: in function </mnt/hgfs/manager/jwtServer/lua/access.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index HTTP/1.1", host: "192.168.121.160"
2017/06/16 14:08:16 [notice] 6835#0: signal process started
2017/06/16 14:08:19 [error] 6836#0: *91 lua entry thread aborted: runtime error: /mnt/hgfs/manager/jwtServer/lua/access.lua:10: module '/mnt/hgfs/manager/jwtServer/lua/waf/waf.lua' not found:
	no field package.preload['/mnt/hgfs/manager/jwtServer/lua/waf/waf.lua']
	no file '/mnt/hgfs/manager/jwtServer/lua/waf//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/opt/openresty/site/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/opt/openresty/site/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua/init.lua'
	no file '/opt/openresty/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/opt/openresty/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua/init.lua'
	no file './/mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/opt/openresty/luajit/share/luajit-2.1.0-beta2//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/usr/local/share/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/usr/local/share/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua/init.lua'
	no file '/opt/openresty/luajit/share/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.lua'
	no file '/opt/openresty/luajit/share/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua/init.lua'
	no file '/opt/openresty/site/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.so'
	no file '/opt/openresty/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.so'
	no file './/mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.so'
	no file '/usr/local/lib/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.so'
	no file '/opt/openresty/luajit/lib/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf/lua.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/opt/openresty/site/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf.so'
	no file '/opt/openresty/lualib//mnt/hgfs/manager/jwtServer/lua/waf/waf.so'
	no file './/mnt/hgfs/manager/jwtServer/lua/waf/waf.so'
	no file '/usr/local/lib/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf.so'
	no file '/opt/openresty/luajit/lib/lua/5.1//mnt/hgfs/manager/jwtServer/lua/waf/waf.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/mnt/hgfs/manager/jwtServer/lua/access.lua:10: in function </mnt/hgfs/manager/jwtServer/lua/access.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index HTTP/1.1", host: "192.168.121.160"
2017/06/16 14:09:58 [notice] 6860#0: signal process started
2017/06/16 14:10:41 [notice] 6864#0: signal process started
2017/06/16 14:10:45 [error] 6865#0: *101 lua entry thread aborted: runtime error: attempt to yield across C-call boundary
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/mnt/hgfs/manager/jwtServer/lua/access.lua:10: in function </mnt/hgfs/manager/jwtServer/lua/access.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index?id=../etc/passwd HTTP/1.1", host: "192.168.121.160"
2017/06/16 14:10:45 [error] 6865#0: *103 lua entry thread aborted: runtime error: /mnt/hgfs/manager/jwtServer/lua/access.lua:10: loop or previous error loading module 'lua.waf.waf'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/mnt/hgfs/manager/jwtServer/lua/access.lua:10: in function </mnt/hgfs/manager/jwtServer/lua/access.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index?id=../etc/passwd HTTP/1.1", host: "192.168.121.160"
2017/06/16 14:10:47 [error] 6865#0: *104 lua entry thread aborted: runtime error: /mnt/hgfs/manager/jwtServer/lua/access.lua:10: loop or previous error loading module 'lua.waf.waf'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/mnt/hgfs/manager/jwtServer/lua/access.lua:10: in function </mnt/hgfs/manager/jwtServer/lua/access.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index?id=../etc/passwd HTTP/1.1", host: "192.168.121.160"
2017/06/16 14:10:52 [notice] 6866#0: signal process started
2017/06/16 14:10:55 [error] 6865#0: *105 lua entry thread aborted: runtime error: /mnt/hgfs/manager/jwtServer/lua/access.lua:10: loop or previous error loading module 'lua.waf.waf'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/mnt/hgfs/manager/jwtServer/lua/access.lua:10: in function </mnt/hgfs/manager/jwtServer/lua/access.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index?id=../etc/passwd HTTP/1.1", host: "192.168.121.160"
2017/06/16 14:10:56 [error] 6867#0: *106 lua entry thread aborted: runtime error: attempt to yield across C-call boundary
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/mnt/hgfs/manager/jwtServer/lua/access.lua:10: in function </mnt/hgfs/manager/jwtServer/lua/access.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index?id=../etc/passwd HTTP/1.1", host: "192.168.121.160"
2017/06/16 14:10:56 [error] 6867#0: *107 lua entry thread aborted: runtime error: /mnt/hgfs/manager/jwtServer/lua/access.lua:10: loop or previous error loading module 'lua.waf.waf'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/mnt/hgfs/manager/jwtServer/lua/access.lua:10: in function </mnt/hgfs/manager/jwtServer/lua/access.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index?id=../etc/passwd HTTP/1.1", host: "192.168.121.160"
2017/06/16 14:10:59 [notice] 6868#0: signal process started
2017/06/16 14:11:05 [error] 6869#0: *108 lua entry thread aborted: runtime error: attempt to yield across C-call boundary
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/mnt/hgfs/manager/jwtServer/lua/access.lua:10: in function </mnt/hgfs/manager/jwtServer/lua/access.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index?id=../etc/passwd HTTP/1.1", host: "192.168.121.160"
2017/06/16 14:11:05 [error] 6869#0: *109 lua entry thread aborted: runtime error: /mnt/hgfs/manager/jwtServer/lua/access.lua:10: loop or previous error loading module 'lua.waf.waf'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/mnt/hgfs/manager/jwtServer/lua/access.lua:10: in function </mnt/hgfs/manager/jwtServer/lua/access.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index?id=../etc/passwd HTTP/1.1", host: "192.168.121.160"
2017/06/16 14:11:06 [error] 6869#0: *110 lua entry thread aborted: runtime error: /mnt/hgfs/manager/jwtServer/lua/access.lua:10: loop or previous error loading module 'lua.waf.waf'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	/mnt/hgfs/manager/jwtServer/lua/access.lua:10: in function </mnt/hgfs/manager/jwtServer/lua/access.lua:1>, client: 192.168.121.1, server: localhost, request: "GET /home/index?id=../etc/passwd HTTP/1.1", host: "192.168.121.160"
2017/06/16 14:13:42 [notice] 6870#0: signal process started
2017/06/16 14:18:34 [notice] 6872#0: signal process started
